name: Documentation deploy
on:
  push:
    branches: ["temp"]
  pull_request:
    branches: ["temp"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: "17"
          maven-version: "3.9.4"
      - name: Build application
        run: mvn clean install
      - name: Generate JavaDoc
        run: mvn javadoc:javadoc
      - name: Generate JaCoCo report
        run: mvn jacoco:report
      - name: Moving JavaDoc and JaCoCo report
        run: |
          rm -rf sites/javadoc/**
          rm -rf sites/jacoco/**
          cp -r target/site/apidocs/** sites/javadoc/
          cp -r target/site/jacoco/** sites/jacoco/
      - name: Deploying to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sites
          

